---
name: Terraform module check
on:
    pull_request:

jobs:
    validate:
        name: Validate Terraform
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
    
            - name: Install Terraform
              uses: hashicorp/setup-terraform@v2
            
            - name: Change into Test directory
              run: cd test
        
            - name: Terraform Format Check
              run: terraform fmt -check
        
            - name: Terraform Init
              run: terraform init -backend=false
        
            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Plan
              run: terraform plan
